### ISSUE TITLE
Hi! database and client with instructions please

### ISSUE THREAD

**Issue by Killua99x** [seppeduwe/cocct#2]
Hi, can you write on readme download url of database, client and instructions to made it work? 
Thanks in advance

**Comment by Multiply** [comment]
This project is long defunct AFAIK, and it is not a CoC server in the sense that you get a private server, but was merely used to sniff out messages to and from CoC's official servers, and made it possible to query data from CoC's internal API's.

**Comment by Killua99x** [comment]
Ah okay, thanks for the info and for the fast reply
